- name: Run command on EC2
  hosts: webservers
  tasks:
    - name: Download httpd
      command: sudo yum install httpd -y

    - name: Start httpd
      command: sudo service httpd start

    - name: Get httpd status
      command: sudo service httpd status
      register: httpd_serv_status
      
    - name: Print httpd status
      debug:
        var: httpd_serv_status.stdout

    - name: Copy files into '/var/www/html'
      shell: sudo mv ~/*.html /var/www/html/ 
