name: ansible-pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Ansible_GA/**'

jobs:
  build:
    name: Run Ansible
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Ansible_GA
    steps:
      - name: Checkout Ansible repo
        uses: actions/checkout@v2
    
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Copy new EC2 instance IP to hosts
        run: |
          for i in {1..3}; do
            IP_ADDR=$(aws ec2 describe-instances --filters "Name=tag:Name, Values=web-host-instance" "Name=instance-state-name, Values=running" --query "Reservations[*].Instances[*].NetworkInterfaces[*].Association.PublicIp" --output text)
            if [ -z "$IP_ADDR" ]; then
              echo "IP not found, retrying..."
              exit 1
            fi
              echo -e "[webserver]\n$IP_ADDR\n" > hosts
              sleep(5)
          done

      - name: Save AWS private key
        run: echo "${{ secrets.AWS_KEY_PAIR }}" > aws_key_pair.pem && chmod 600 aws_key_pair.pem

      - name: Debug files
        run: ls -lrth

      - name: Run ansible
        run: ansible-playbook -i hosts playbook.yaml -u ec2-user --private-key aws_key_pair.pem --ssh-extra-args="-o StrictHostKeyChecking=no"

          