name: terraform-create-pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Terraform_GA/**'

jobs:
  build:
    name: Run Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Terraform_GA
    steps:
      - name: Check out Terraform repository
        uses: actions/checkout@v2

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup/Install Terraform
        id: setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.2.0"

      - name: Initialize Terraform
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      # - name: Terraform Plan
      #   id: plan
      #   run: terraform plan 

      # - name: Terraform apply
      #   id: apply
      #   run: terraform apply -auto-approve

      # - name: Trigger ansible workflow
      #   id: trigger
      #   uses: benc-uk/workflow-dispatch@v1
      #   with:
      #     workflow: ansible-pipeline.yml
      #     repo: Ajtambad/Terraform-Ansible-Project
      #     ref: main

      - name: Trigger ansible workflow
        id: trigger
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/Ajtambad/Terraform-Ansible-Project/actions/workflows/ansible-pipeline.yml/dispatches \
          -d '{"ref":"main"}'

