name: Terraform-Ansible Pipeline
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: development
        required: true
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'Ansible_GA/**'
  #     - 'Terraform_GA/**'
  #     - 'Website/**'

jobs:
  build:
    name: Run Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Check out Terraform repository
        uses: actions/checkout@v2
        with:
          sparse_checkout: |
            Terraform_GA

      - name: Setup/Install Terraform
        id: setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_versions: "1.2.0"

      - name: Initialize Terraform
        id: init
        run: terraform init

      - name: Terraform Fotmat
        id: fmt
        run: terraform fmt -check

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan 

